# Generated by Django 3.2.15 on 2022-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_imagesapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesapp',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
